bakeware/lib/bakeware/assembler.ex
Fixes #38 by following existing release patterns to make it feel more at home, but more importantly show the path more prominently. 
End result looks like:
```
Bakeware successfully assembled executable at: 
_build/prod/rel/bakeware/simple_script
Release created at _build/prod/rel/simple_script!
_build/prod/rel/simple_script/bin/simple_script start
Once the release is running:
_build/prod/rel/simple_script/bin/simple_script remote
_build/prod/rel/simple_script/bin/simple_script stop
To list all commands:
_build/prod/rel/simple_script/bin/simple_script
```
=> Improve visibility for the bakeware executable path

bakeware/lib/bakeware/script.ex, bakeware/test/bakeware/script_test.exs, bakeware/test/bakeware_test.exs
I ran into some problems when trying to run `iex -S mix` if the main app was a `Bakeware.Script`.
Regardless of the usage, this PR aims to give a more informative error if the variable is set incorrectly.
I also took the opportunity to reduce the size of the macro. This made it easier to unit test the module.
=> fix: do not require bakeware argc

CHANGELOG.md, mix.exs
The intention of this release is to start using hex.pm for code distribution. My hope is that since people are posting articles about using Bakeware that they can reference the releases instead of our `main` branch.
=> v0.1.1 release

Makefile, lib/bakeware/assembler.ex
Even though we're telling people to set `runtime: false` when they
depend on `:bakeware`, it's easy to forget. If you forget, then the
launcher code is included twice - once in the right place and again
inside of the OTP release. By moving the launcher code outside of the
`priv` directory, it no longer gets included in the release for
`runtime: true`.
This also lets us experiment with including runtime code in Bakeware
without bloating the generated binaries as much. For reference, here are
the current release contents for `runtime: true`:
```
bakeware-0.1.1
└── ebin
├── bakeware.app
├── Elixir.Bakeware.Assembler.beam
├── Elixir.Bakeware.beam
├── Elixir.Bakeware.Script.beam
└── Elixir.Mix.Tasks.Bakeware.Assemble.beam
```
=> Move launcher code out of priv

lib/bakeware/script.ex, test/bakeware_script_test.exs
This was initially done in f0eb507ee142f45b08533a57744c516aa529d5b4 by @polvalente but introduced an unforseen bug.
Building on their example, this again removes the requirement for argc for the desired behavior of being able to run changes locally for testing.
It also follows the pattern to reduce the amount of code in the __using__ macro for scripts and allows easier unit testing
=> Fix requirement on argc

examples/iex_prompt/mix.exs, examples/nif_script/mix.exs, examples/phoenix_app/mix.exs, examples/scenic_app/mix.exs, examples/simple_app/mix.exs, examples/simple_script/mix.exs
Here's an example of what it looked like before:
```
Generated iex_prompt app
* assembling iex_prompt-0.1.0 on MIX_ENV=prod
* skipping runtime configuration (config/runtime.exs not found)
* assembling bakeware iex_prompt
Bakeware successfully assembled executable at:
_build/prod/rel/bakeware/iex_prompt
Release created at _build/prod/rel/iex_prompt!
_build/prod/rel/iex_prompt/bin/iex_prompt start
Once the release is running:
_build/prod/rel/iex_prompt/bin/iex_prompt remote
_build/prod/rel/iex_prompt/bin/iex_prompt stop
To list all commands:
_build/prod/rel/iex_prompt/bin/iex_prompt
```
After:
```
Generated iex_prompt app
* skipping runtime configuration (config/runtime.exs not found)
* assembling bakeware iex_prompt
Bakeware successfully assembled executable at: …
```
=> Add "quiet: true" to reduce build output

Makefile, src/cache.c, src/utils.c
_GNU_SOURCE is needed for asprintf(3). Rather than define it at the top
of every C file that needs it, this moves it to one place in the
Makefile.
=> Move _GNU_SOURCE definition to Makefile

Makefile, README.md, lib/bakeware/assembler.ex, src/bakeware.h, src/cache.c, src/main.c, src/sha1.c, src/sha1.h, src/sha_read.c, src/trailer.c, src/unzstd.c
During SpawnFest, we used SHA-256 to create deterministic and unique directory names in the cache. Due to lack of time, we never validated the checksums of the archive. We also never discussed whether SHA-256 was appropriate.
This change adds verification and shortens the hash to SHA-1. The logic is that SHA-256 isn't needed and standalone SHA-1 implementations are easy-to-find in C. The bakeware archive trailer still has enough bytes reserved to return to SHA-256 if ever needed.
A side effect is that the cache directories names are a little shorter. 
NOTE: Tests are coming shortly after this PR.
=> Switch cache directory naming to SHA-1 and verify

README.md, examples/iex_prompt/rel/env.bat.eex, examples/iex_prompt/rel/env.sh.eex, examples/iex_prompt/rel/vm.args.eex, examples/nif_script/rel/env.bat.eex, examples/nif_script/rel/env.sh.eex, examples/nif_script/rel/vm.args.eex, examples/scenic_app/rel/env.bat.eex, examples/scenic_app/rel/env.sh.eex, examples/scenic_app/rel/vm.args.eex, examples/simple_app/rel/env.bat.eex, examples/simple_app/rel/env.sh.eex, examples/simple_app/rel/vm.args.eex, examples/simple_script/rel/env.bat.eex, examples/simple_script/rel/env.sh.eex, examples/simple_script/rel/vm.args.eex
Short-lived applications probably don't want Erlang distribution enabled
by default. In addition to adding some startup time (hard to notice in
my testing), it also prevents multiple instances of Bakeware apps from
running. Here's the error that you get:
```
$ _build/prod/rel/bakeware/iex_prompt
Protocol 'inet_tcp': the name iex_prompt@sprint seems to be in use by another Erlang node
```
This commit turns off Erlang distribution in everything except for the
Phoenix app. It also adds a note to the `README.md` about it.
=> Add Erlang distribution docs and disable on most examples

README.md, lib/bakeware/assembler.ex, lib/bakeware/cpio.ex
Resolves https://github.com/bake-bake-bake/bakeware/issues/85
Allows you to set the compression level for a bakeware release.
Currently looks for the `:compression_level` option key. I debated scoping that to `bakeware: [compression_level: 15]`, but ultimately left it at the root. What do you think?
Also updates the example scripts to lower compression for CI
=> Compression level

src/main.c
If you include a `--bw-*` arg that will continue running the program (such as `--bw-gc`), this check would fail and cause a segfault.
=> fix attempt to check argv slot check

README.md, examples/iex_prompt/lib/iex_prompt.ex, examples/iex_prompt/mix.exs, lib/bakeware/assembler.ex, src/bakeware.h, src/main.c, src/trailer.c, test/bakeware_test.exs, test/fixtures/command_test/.gitignore, test/fixtures/command_test/lib/rel_test/application.ex, test/fixtures/command_test/mix.exs, test/fixtures/command_test/rel/env.bat.eex, test/fixtures/command_test/rel/env.sh.eex, test/fixtures/command_test/rel/vm.args.eex
This extracts the start command support in the trailer from PR #92, adds a unit
test to verify that it works, and updates the iex_prompt example to use it.
The iex_prompt example now supports the arrow keys, history, etc., that you
expect to have at the prompt. This avoids the needs to use `rlwrap` to add this
functionality back in. I also updated the release spec to keep the help docs
since those are nice to have and don't bloat the image all that much.
=> Support changing the release script start command

src/bakeware.h, src/main.c, test/bakeware_test.exs
Resolves #91
Allows one to specify a mix release command to use with `--mix-{CMD}`
This is currently producing a Seg fault, but at least getting it up for someone better at C than me to look at why. (Or I will revisit when time allows)
=> Support Mix release commands

.github/workflows/main.yml
This includes runners for Ubuntu and MacOS that came with the script
that I started with from the Benchee project. If we move CI completely
over to GitHub Actions, this hopefully will save some time.
=> Enable GitHub Actions for Windows CI builds

Makefile, README.md, lib/bakeware/assembler.ex, src/bakeware.h, src/cache.c, src/cpio.c, src/main.c, src/rm_fr.c, src/sha1.c, src/sha_read.c, src/trailer.c, src/unzstd.c, src/utils.c
I have got this working with mingw on windows. My environment has elixir and mingw installed via chocolatey.
Changes:
+ Windows needs `O_BINARY` flag for reading cpio which is absent in unix, otherwise it encounters unexpected EOF.
+ mkdtemp(absent in windows) replaced with mktemp and mkdir.
+ mkdir takes only 1 argument in mingw and msvc header files where as posix mkdir takes 2 arguments, so added a macro to replace the call having 2 arguments with 1.
+ gcc `-pipe -Wl,-o` to remove automatically added `.exe` extension in intermediate launcher binary.
+ Add `.exe` to the final binary in case of windows.
No luck with MSVC due to non-availability of a drop-in replacement for unistd.h in windows.
Fixes bake-bake-bake/bakeware#37
=> Windows Support

README.md, examples/iex_prompt/mix.exs, lib/bakeware/assembler.ex, test/fixtures/command_test/mix.exs, test/fixtures/rel_test/mix.exs
I've debated this on and off and now I'm more on the side of avoiding clashing options with Mix releases. So this scopes all the release options to a `:bakeware` key in the release to allow us to add/remove options without having to worry about what might be done with Mix releases
=> Scope bakeware release options to :bakeware

Makefile, README.md, lib/bakeware/assembler.ex
This PR allows the user to run commands from PowerShell and cmd.exe, in addition to MinGW, which is the current requirement. The readme has also been expanded for Windows.
=> Improve/expand Windows compatibility

.circleci/config.yml, .github/workflows/main.yml, lib/bakeware.ex, lib/bakeware/assembler.ex, lib/bakeware/script.ex
* bump workflow OTP and Elixir versions
* fix formatting
* Use CircleCI only for example testing
* Most of the CI has been moved to Github Workflow. However, example
testing still occurs in CircleCI. This removes the need to do the
typical build process there and instead only compiles examples. It
attempts the simplest example compile first and then will try all the
rest in order to reduce overloading MacOS and other compute/build times
=> Quick fixes

lib/bakeware/assembler.ex
fixes #118
`type` command fails silently, resulting in an empty executable
=> allow for spaces in paths for windows

.github/workflows/main.yml, Makefile
This PR changes the GitHub Actions for Windows so that the `cmd`, `pwsh` and `msys2` shells are all used to build and test the project.
The `MakeFile` is modified so that `SHELL=cmd` on Windows, as I was getting failures due to the difference between `mkdir` (windows) and `mkdir -p` (unix) in CI.
We use `scoop` instead of `chocolatey`, as the Elixir package on `scoop` is maintained.  In my experience, `chocolatey` is awash with unmaintained packages.
We don't both installing `zstd` or `make` as they're preinstalled on GitHub Actions Windows builds.  We could probably use the pre-installed `msys2` but I had better luck with this action.
=> test on cmd, pwsh and msys2 in windows ci

Makefile, src/main.c
Fixes #122 
* Use initial 'for' loop delcarations for systems without C99 mode set
* reduce prints in the Makefile
=> initial for loop declarations and reduce Makefile prints

lib/bakeware/cpio.ex
I am not sure why `:all` was removed in elixir 1.13 but `:eof` breaks beh on empty files by returning atom `:eof` this makes the subsequent `binwrite` fail.
=> fix binread eof
